### ISSUE TITLE
Update to v60

### ISSUE THREAD

**Issue by a1russell** [TanmanG/LethalCompany-NonLethalCompany#1]
Hello, I am hoping that you will continue maintaining your mod, as I appreciate using it very much. The v50 update that was recently released introduced a new weapon, the kitchen knife. This kitchen knife generates a lot of blood when used, so it appears this mod needs to be updated to account for that.

Another 2 potential sources that I didn't test:
* You can now be decapitated by flying into the overhead fan at the entrance of the factory.
* There is a new spike trap which can crush players and get them stuck on the trap.

**Comment by DVGutierrez** [comment]
My friends and I love this mod. How can you tell me how you modded it? I'd like to try to continue updating this mod if possible.
We all here, back where I live, also hope that this mod gets an update some time in the future :)

**Comment by Gweneg** [comment]
Converted this to a milestone.
